version: '3.8'

services:
  youtube-live-downloader:
    build: .
    container_name: youtube-live-downloader
    ports:
      - "5000:5000"
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    restart: unless-stopped
    volumes:
      - ./data:/app/data
